targetNamespace: ''
parameters: {}
packages:
  - name: resolver
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: dns
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
